[build]
  functions = "functions"  # Directory where Netlify will look for serverless functions

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/socket.js/:splat"
